name: base
channels:
  - conda-forge
dependencies:
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - ipython
  - python
  - numpy
  - pip
  - future
  - pandas
  - ipywidgets
  - seaborn
